baseURL = "https://aiseeeeel.github.io/web-portfolio/"
languageCode = "en-gb"
defaultContentLanguage = "en-gb"
title = "My portfolio"
theme = "ananke"

enableRobotsTXT = true

[params]
  description = "Portfolio"
  author = "Agalarova Aisel"
  background_color_class = "bg-light-blue"
  custom_css = ["custom.css"]
  read_more_copy = "Read more"
  

[menu]

  [[menu.main]]
    name = "Main"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Http Lab"
    url = "/http-lab/http/"
    weight = 3  

  [[menu.main]]
    name = "Time Task"
    url = "/time/"
    weight = 4   

  [[menu.main]]
    name = "Webpack"
    url = "/webpack-lab/webpack/"
    weight = 5    
