baseURL = "https://aiseeeeel.github.io/web-portfolio/"
languageCode = "ru"
title = "Портфолио"
theme = "hugo-developer-portfolio"

canonifyURLs = true

[params]
  home = "Главная"

  description = "Это мое портфолио, где я собираю свои работы, проекты и учебные достижения."
  author = "Айсел Агаларова"

  # Социальные сети
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/aiseeeeel"

[menu]
  [[menu.main]]
    name = "Обо мне"
    url = "/web-portfolio/about/"
    weight = 1